"""
Segmentation Upid Examples
"""

import threefive

ADI = "/DBEAAAAAAAA///wBQb+AFJlwAAuAixDVUVJYgAFin+/CR1TSUdOQUw6My1zUTROZ0ZUME9qUHNHNFdxVVFvdzUAAEukzlg="
ADS2 = '/DBUAAAAAAAA///wBQb+Lom5UgA+AjxDVUVJAAAAC3+/Di1BRFMtVVBJRDphYTg1YmJiNi01YzQzLTRiNmEtYmViYi1lZTNiMTNlYjc5OTkRAAAO7LCw'

ADID = (
    '/DA4AAAAAAAA///wBQb+AKpFLgAiAiBDVUVJAAAAA3//AAApPWwDDEFCQ0QwMTIzNDU2SBAAABZE5vg='
)
AIRID = "/DBhAAAAAAAA///wBQb+qM1E7QBLAhdDVUVJSAAArX+fCAgAAAAALLLXnTUCAAIXQ1VFSUgAACZ/nwgIAAAAACyy150RAAACF0NVRUlIAAAnf58ICAAAAAAsstezEAAAihiGnw=="
ATSC = (
'/DA4AAAAAAAA///wBQb+QjoOtgAiAiBDVUVJAAAAA3//AAApPWwLDADx7/9odW1hbjAxMhAAABdHvhE='
)
EIDR = (
    '/DA4AAAAAAAA///wBQb+AKpFLgAiAiBDVUVJAAAAA3//AAApPWwKDDB4MTQ3OGY4NWFlMRAAAGXOtak='
)
ISAN = (
    '/DA4AAAAAAAA///wBQb+Lom5UgAiAiBDVUVJAAAABn//AAApPWwGDAAAAAA6jQAAAAAAABAAAHGXrpg='
)
MID = "/DA9AAAAAAAAAACABQb+0fha8wAnAiVDVUVJSAAAv3/PAAD4+mMNEQ4FTEEzMDkICAAAAAAuU4SBNAAAPIaCPw=="
MPU = "/DCSAAAAAAAAAP/wBQb/RgeVUgB8AhdDVUVJbs6+VX+/CAgAAAAABy0IxzELGQIXQ1VFSW7MmIh/vwgIAAABGDayFhE3AQECHENVRUluzw0If/8AABvLoAgIAAAAAActVhIwDBkCKkNVRUluzw02f78MG1JUTE4xSAEAAAAAMTM3NjkyMDI1NDQ5NUgxAAEAAGnbuXg="
TID2 = "/DAzAAAAAAAA///wBQb+AAQesAAdAhtDVUVJAAAAA3+/BwxNVjAwMDQxNDY0MDARAAAf8lPm"


dmesg = [ADI, ADS2, ADID, AIRID, ATSC, EIDR, ISAN, MID, MPU,]

ids = []


def stuff(t, upid):
    if t not in ids:
        ids.append(t)
        print(f"\033[92m{hex(t)}\033[0m : {upid}")


for m in dmesg:
    tf = threefive.Cue(m)
    tf.decode()
    _ = [stuff(d.segmentation_upid_type, d.segmentation_upid) for d in tf.descriptors]
